version: '3'

services:
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: Root@123
        MYSQL_DATABASE: magento
        MYSQL_USER: magento
        MYSQL_PASSWORD: Magento@123
    volumes:
      - /var/www/html/db/db80:/var/lib/mysql