version: '3'

services:
  web:
    build: .
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    links:
      - db
    networks:
      - magento2-docker-network
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: magento
        MYSQL_USER: magento
        MYSQL_PASSWORD: magento
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - magento2-docker-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOST=db
     - MYSQL_ROOT_PASSWORD=password
    ports:
     - 8080:80
    depends_on:
      - db
    networks:
        - magento2-docker-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - magento2-docker-network

networks:
  magento2-docker-network:
    driver: bridge

