version: "3.8"

services:
  nginx:
    image: nginx:1.28-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../code:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - magento2-docker-network

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    expose:
      - "9000"
    environment:
      MAGE_MODE: ${MAGE_MODE}
    volumes:
      - ../code:/var/www/html
    depends_on:
      - db
    networks:
      - magento2-docker-network

  db:
    image: mariadb:11.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - magento2-docker-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - magento2-docker-network

  opensearch-node1:
    image: opensearchproject/opensearch:3
    environment:
      cluster.name: opensearch-cluster
      node.name: opensearch-node1
      discovery.seed_hosts: opensearch-node1,opensearch-node2
      cluster.initial_cluster_manager_nodes: opensearch-node1,opensearch-node2
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./opensearch-data/node1:/usr/share/opensearch/data
    ports:
      - "9200:9200"
    networks:
      - magento2-docker-network

  opensearch-node2:
    image: opensearchproject/opensearch:3
    environment:
      cluster.name: opensearch-cluster
      node.name: opensearch-node2
      discovery.seed_hosts: opensearch-node1,opensearch-node2
      cluster.initial_cluster_manager_nodes: opensearch-node1,opensearch-node2
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: ${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./opensearch-data/node2:/usr/share/opensearch/data
    networks:
      - magento2-docker-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    ports:
      - "5601:5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200","http://opensearch-node2:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
    depends_on:
      - opensearch-node1
      - opensearch-node2
    networks:
      - magento2-docker-network

  rabbitmq:
    image: rabbitmq:4.1-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - magento2-docker-network

networks:
  magento2-docker-network:
    driver: bridge