date.timezone=America/New_York
memory_limit=4G

; Performance
realpath_cache_size=10M
realpath_cache_ttl=7200

; OPcache
opcache.enable=1
opcache.memory_consumption=512
opcache.max_accelerated_files=65406
opcache.validate_timestamps=1
opcache.revalidate_freq=2
opcache.save_comments=1

; Execution
max_execution_time=1800
max_input_time=1800

; Uploads
upload_max_filesize=64M
post_max_size=64M

; Sessions
session.gc_maxlifetime=86400